title: Knowledge Rules GitHub Documentation
email: marc.weeber@deltares.nl
description:
nav_order: 3


# Build settings
theme: jekyll-theme-cayman

# Reading Files
include:
  - docs

#Navigation
header_pages:
 - /docs/1_quick_start/
 - /docs/2_a_guid_to_this_manual/
 - /docs/3_knowledge_rules_github.md/
 - /docs/4_knowledge_rules_files_and_structure/
 - /docs/5_supporting_tools/
 - /docs/6_model_adapters/
 - /docs/7_FAQ/ 

