title: Knowledge Rules
email: marc.weeber@deltares.nl
description: Knowledge rules GitHub Documentation



# Build settings
remote_theme: pmarsceill/just-the-docs
search-enabled: true


# Reading Files
include:
  - docs
  
# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "KnowledgeRules GitHub":
    - "//github.com/Deltares/KnowledgeRules"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

#Navigation
#defaults:
#  # _docs
##  - scope:
#      path: ""
#      type: docs
#    values:
#      sidebar:
#        nav: "docs"

# header_pages:
#  - /docs/1_quick_start/
#  - /docs/2_a_guid_to_this_manual/
#  - /docs/3_knowledge_rules_github.md/
#  - /docs/4_knowledge_rules_files_and_structure/
#  - /docs/5_supporting_tools/
#  - /docs/6_model_adapters/
#  - /docs/7_FAQ/ 

